#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

pkill -u $USER '^compton$'

#Autostart application
#compton
compton  --config $HOME/.config/compton.conf &

#polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

#Simple X hotkex daemon autostart
sxhkd &

#  xsetroot -solid '#5A8E3A'
xsetroot -solid '#285577'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier


# ALT + Keys / Variety Keys
#--------------------------
hc keybind Mod1-f spawn variety -f
hc keybind Mod1-n spawn variety -n
hc keybind Mod1-p spawn variety -p
hc keybind Mod1-t spawn variety -t
hc keybind Mod1-Up spawn variety --pause
hc keybind Mod1-Down spawn variety --resume
hc keybind Mod1-Left spawn variety -p
hc keybind Mod1-Right spawn variety -n
hc keybind Mod1-v spawn variety --preferences
hc keybind Mod1-s spawn variety --selector
#--------------------------
# SHIFT + ALT Keys / Variety Keys for PY-WAL  / these will change wallpaper and grab colors with PY-WAL
#--------------------------
hc keybind Mod1-Shift-f spawn $HOME/.config/herbstluftwm/scripts/set-pywal.sh -f
hc keybind Mod1-Shift-p spawn $HOME/.config/herbstluftwm/scripts/set-pywal.sh -p
hc keybind Mod1-Shift-n spawn $HOME/.config/herbstluftwm/scripts/set-pywal.sh -n
hc keybind Mod1-Shift-u spawn $HOME/.config/herbstluftwm/scripts/set-pywal.sh -u


# tags

tag_names=( {"  1  ","  2  ","  3  ","   4  ","  5  ","  6  "," 7  ","  8  ","  9  "} )
tag_icons=( {"  1  ","  2  ","  3  ","   4  ","  5  ","  6  "," 7  ","  8  ","  9  "} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done


# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all


# thee
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#015697'
hc set frame_border_normal_color '#101010'
#hc set frame_bg_normal_color '#565656'
#hc set frame_bg_active_color '#345F0C'

#hc set frame_bg_active_color '#5555FF'
hc set frame_bg_active_color '#0B0B21'
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1      #if 0 no transparency
hc set frame_transparent_width 0
hc set frame_gap 0
hc set focus_follows_mouse 1

#Customize (colour) herbstluftwm
#hc attr theme.active.color '#9fbc00'
hc attr theme.active.color '#015697'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3      #windows border width
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
#hc attr theme.active.inner_color '#3E4A00'
#hc attr theme.active.outer_color '#3E4A00'
hc attr theme.active.inner_color '#0B0B21'
hc attr theme.active.outer_color '#285577'
hc attr theme.background_color '#141414'

#Bar & window gaps
hc pad 0 30 0 0
hc set window_gap 20
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

#Rules
hc unrule -F
# hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on
# normally focus new clients
# hc rule focus=off
# normally do not focus new clients
# give focus to most common terminals
# hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on

hc rule class=Firefox tag=^1
hc rule class='discord' tag=2 focus=on

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=on


hc set tree_style '⊙│ ├╰»─╮'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors


# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
